### ISSUE TITLE
Usage of the library

### ISSUE THREAD

**Issue by nouhouari** [eficode/JavaFXLibrary#35] opened 2020-08-29 11:18 UTC
Hi,
I'm trying to use the library and test a JavaFX application.
I'm running the library in remote mode and I'm able to "connect" from a robot test. 
My robot framework is running into a Docker container.

I've added this in my test and I don't see any error message.
`Library  Remote    http://192.168.0.143:8270    WITH NAME    JavaFXLibrary`

Now, it's not clear on how I should test my JavaFX application.

I've added a dummy test case to see what happen
`*** Test Cases ***
JavaFX Test 
   Capture Image`

Do I need to embed the library into my app to make it work (and call the library API to start the server)
Or will the library "talk" to my JavaFX application locally ?

Thank you for your help.

**Comment by psaikkonen** [comment] 2020-08-31 06:43
Hi!
Currently the library can't attach to an application that is already running, so the AUT (application under test) needs to be launched using library keyword [Launch JavaFX Application](https://repo1.maven.org/maven2/org/robotframework/javafxlibrary/0.5.4/javafxlibrary-0.5.4.html#Launch%20Javafx%20Application). Both JavaFXLibrary and AUT should be added to java classpath so the library can launch the application.

In the remote mode JavaFXLibrary and AUT are located in the same machine, and the Robot Framework execution is managed elsewhere. See Robot Frameworks [Remote library interface](https://github.com/robotframework/RemoteInterface) for more details on this.

So for example let's say we have JavaFXLibrary running at 192.168.0.143:8270 with access to our AUT testapp. Here is how the robot test file would look like:

```*** Settings ***
Library           Remote    http://192.168.0.143:8270    WITH NAME    JavaFXLibrary
Suite Setup       Launch JavaFX Application    testapp.jar
Suite Teardown    Close JavaFX Application

*** Test Cases ***
JavaFX Test
    Capture Image
```

Alternatively Launch JavaFX Application can be called using a class:
```Suite Setup | Launch JavaFX Application | com.example.TestApp```

**Comment by sampeson** [comment] 2020-08-31 12:56
Not a bug, closing...

**Closed by sampeson** 2020-08-31 12:56 UTC
